### ISSUE TITLE
test_fillet_common fails with RuntimeError: StdFail_NotDone

### ISSUE THREAD

**Issue by guillaume-florent** [osv-team/ccad#9]
ERROR: test_fillet_common (model_unittest.TestSolidFunctions)

Traceback (most recent call last):
  File "/opt/build/ccad/unittest/model_unittest.py", line 228, in test_fillet_common
    s3 = cm.fillet_common(s1, s2, 0.25)
  File "/opt/conda/lib/python3.6/site-packages/ccad/model.py", line 1032, in fillet_common
    _BRepAlgoAPI.BRepAlgoAPI_Common(s1.shape, s2.shape), rad)
  File "/opt/conda/lib/python3.6/site-packages/ccad/model.py", line 962, in _fillet_boolean
    b3 = b2.Shape()
RuntimeError: StdFail_NotDone
BRep_API: command not done

**Comment by guillaume-florent** [comment]
Shapes in the test did not intersect and the computed volume was wrong.
